# Generated by Django 5.1.6 on 2025-02-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_profile_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ente_promotore', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('soglia_minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soglia_massima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soglia_versata', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ha_raggiunto_minimo', models.BooleanField(default=False)),
                ('completata', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
